### PR TITLE
Enhanced the rev.erl code, sharing multiple streams on the same conne…

### PR DESCRIPTION
**Pull request by klacke**
…ction

I enhanced the rev.erl code making it more interesting. I also added a test and a README.md file

### CODE REVIEW

**Comment by klacke** [comment]
Question:  I should be using the handoff code as well, shouldn't I

**Comment by klacke** [comment]
Yes, I see now, quicer:handoff_stream/3 should be used, 
I think that maybe quicer:controlling_process should do what handoff_stream does, instead of a new function. It's also confusing to still export controlling_process if it shouldn't be used. OTOH, I guess it stlll should be used for Connections, yes ?

**Comment by klacke** [comment]
I'll change the code to use handoff_stream instead

**Comment by qzhuyan** [comment]
thanks for the PR! 
>I think that maybe quicer:controlling_process should do what handoff_stream does, instead of a new function. It's also confusing to still export controlling_process if it shouldn't be used. OTOH, I guess it stlll should be used for Connections, yes ?

thanks for the suggestion, yes `controlling_process` could be used for both streams and connections.
We need handoff_connecion for connection, too.

**Review by qzhuyan — APPROVED** [review]

**Pull request merged**
