### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by qzhuyan** [comment]
@kianmeng thanks for the PR, would you share the tool you use to find the typos? thanks.

**Comment by qzhuyan** [comment]
@kianmeng thanks for the PR, would you share the tool you use to find the typos? thanks.

**Comment by kianmeng** [comment]
@qzhuyan 

Using https://github.com/codespell-project/codespell.
You can add a GitHub Action for it, based on https://github.com/codespell-project/actions-codespell

**Review by qzhuyan — APPROVED** [review]

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
